# Generated by Django 6.0.3 on 2026-03-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/gallery/')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='courses.course')),
            ],
            options={
                'verbose_name': 'Imagen del curso',
                'verbose_name_plural': 'Imágenes del curso',
                'ordering': ['order'],
            },
        ),
    ]
