# Generated by Django 6.0.3 on 2026-03-18 04:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
