# Generated by Django 6.0.3 on 2026-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_cloudinary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.URLField(),
        ),
    ]
